name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew || find . -name "gradlew" -exec chmod +x {} \;

    - name: Build APK with Gradle
      run: |
        if [ -f "./gradlew" ]; then
          ./gradlew assembleDebug
        else
          DIR=$(find . -name "gradlew" -exec dirname {} \; | head -n 1)
          cd "$DIR"
          ./gradlew assembleDebug
        fi

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sai-Shakti-School-App
        path: '**/app/build/outputs/apk/debug/app-debug.apk'
        
